START
PARSED
[
  ["E", "", "html", ""],
  ["E", "", "head", ""],
  [
    "E",
    "",
    "meta",
    " HTTP-EQUIV=\"content-type\" CONTENT=\"text/html; charset=ISO-8859-2\"",
  ],
  ["E", "", "title", ""],
  [
    "T",
    "Vyhledat Googlem: &quot;digitalni velkoplosny tisk&quot; ",
  ],
  ["E", "/", "title", ""],
  ["E", "", "style", ""],
  [
    "C",
    "\nbody,td,div,.p,a{font-family:arial,sans-serif }\ndiv,td{color:#000}\n.f,.fl:link{color:#6f6f6f}\na:link,.w,a.w:link,.w a:link{color:#00c}\na:visited,.fl:visited{color:#551a8b}\na:active,.fl:active{color:#f00}\n.t a:link,.t a:active,.t a:visited,.t{color:#000}\n.t{background-color:#e5ecf9}\n.k{background-color:#36c}\n.j{width:33em}\n.h{color:#36c}\n.i,.i:link{color:#a90a08}\n.a,.a:link{color:#008000}\n.z{display:none}\ndiv.n {margin-top: 1ex}\n.n a{font-size:10pt; color:#000}\n.n .i{font-size:10pt; font-weight:bold}\n.q a:visited,.q a:link,.q a:active,.q {color: #00c; }\n.b{font-size: 12pt; color:#00c; font-weight:bold}\n.ch{cursor:pointer;cursor:hand}\n.e{margin-top: .75em; margin-bottom: .75em}\n.g{margin-top: 1em; margin-bottom: 1em}\n//",
  ],
  ["T", "\n"],
  ["E", "/", "style", ""],
  ["T", "\n"],
  ["E", "", "script", ""],
  [
    "C",
    "\nfunction ss(w){window.status=w;return true;}\nfunction cs(){window.status='';}\nfunction ga(o,e) {return true;}\n//",
  ],
  ["T", "\n"],
  ["E", "/", "script", ""],
  ["T", "\n"],
  ["E", "/", "head", ""],
  ["E", "", "body", " bgcolor=#ffffff topmargin=2 marginheight=2"],
  ["E", "", "table", " border=0 cellpadding=0 cellspacing=0"],
  ["E", "", "tr", ""],
  ["E", "", "td", " valign=top"],
  ["E", "", "a", " href=http://www.google.com/webhp?hl=cs"],
  [
    "E",
    "",
    "img",
    " src=images/logo_sm.gif width=150 height=55 alt=\"P\370ejdi na domovskou str\341nku\" border=0 vspace=12",
  ],
  ["E", "/", "a", ""],
  ["E", "/", "td", ""],
  ["E", "", "td", ""],
  ["T", "&nbsp;&nbsp;"],
  ["E", "/", "td", ""],
  ["E", "", "td", " valign=top"],
  ["E", "", "table", " cellpadding=0 cellspacing=0 border=0"],
  ["E", "", "tr", ""],
  ["E", "", "td", " colspan=2 height=14 valign=bottom"],
  ["E", "", "table", " border=0 cellpadding=4 cellspacing=0"],
  ["E", "", "tr", ""],
  ["E", "", "td", " class=q"],
  ["E", "", "font", " size=-1"],
  ["E", "", "font", " color=#000000"],
  ["E", "", "b", ""],
  ["T", "Web"],
  ["E", "/", "b", ""],
  ["E", "/", "font", ""],
  ["T", "&nbsp;&nbsp;&nbsp;&nbsp;"],
  [
    "E",
    "",
    "a",
    " id=t1a class=q href=http://images.google.com/images?q=%22digitalni+velkoplosny+tisk%22&hl=cs&lr=&ie=UTF-8&inlang=pl&sa=N&tab=wi ",
  ],
  ["T", "Obr\341zky"],
  ["E", "/", "a", ""],
  ["T", "&nbsp;&nbsp;&nbsp;&nbsp;"],
  [
    "E",
    "",
    "a",
    " id=t2a class=q href=http://groups.google.com/groups?q=%22digitalni+velkoplosny+tisk%22&hl=cs&lr=&ie=UTF-8&inlang=pl&sa=N&tab=wg ",
  ],
  ["T", "Skupiny"],
  ["E", "/", "a", ""],
  ["T", "&nbsp;&nbsp;&nbsp;&nbsp;"],
  [
    "E",
    "",
    "a",
    " id=t3a class=q href=http://www.google.com/search?q=%22digitalni+velkoplosny+tisk%22&hl=cs&lr=&ie=UTF-8&inlang=pl&sa=N&cat=gwd/Top&tab=wd ",
  ],
  ["T", "Adres\341\370"],
  ["E", "/", "a", ""],
  ["T", "&nbsp;&nbsp;&nbsp;&nbsp;"],
  ["E", "/", "font", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "/", "table", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "", "tr", ""],
  ["E", "", "td", " nowrap"],
  ["E", "", "form", " name=gs method=GET action=/search"],
  ["E", "", "input", " type=hidden name=hl value=\"cs\""],
  ["E", "", "input", " type=hidden name=inlang value=\"pl\""],
  ["E", "", "input", " type=hidden name=ie value=\"ISO-8859-2\""],
  [
    "E",
    "",
    "input",
    " type=text name=q size=41 maxlength=2048 value=\"&quot;digitalni velkoplosny tisk&quot;\"",
  ],
  ["E", "", "font", " size=-1"],
  ["T", " "],
  [
    "E",
    "",
    "input",
    " type=submit name=\"btnG\" value=\"Vyhledat Googlem\"",
  ],
  ["E", "", "span", " id=hf"],
  ["E", "/", "span", ""],
  ["E", "/", "font", ""],
  ["E", "/", "td", ""],
  ["E", "", "td", " nowrap"],
  ["E", "", "font", " size=-2"],
  ["T", "&nbsp;&nbsp;"],
  [
    "E",
    "",
    "a",
    " href=/advanced_search?q=%22digitalni+velkoplosny+tisk%22&hl=cs&lr=&ie=UTF-8&inlang=pl",
  ],
  ["T", "Pokro\350il\351 vyhled\341v\341n\355"],
  ["E", "/", "a", ""],
  ["E", "", "br", ""],
  ["T", "&nbsp;&nbsp;"],
  [
    "E",
    "",
    "a",
    " href=/preferences?q=%22digitalni+velkoplosny+tisk%22&hl=cs&lr=&ie=UTF-8&inlang=pl",
  ],
  ["T", "Nastaven\355"],
  ["E", "/", "a", ""],
  ["T", "&nbsp;&nbsp;&nbsp;&nbsp;"],
  ["E", "/", "font", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "/", "table", ""],
  ["E", "", "table", " cellpadding=0 cellspacing=0 border=0"],
  ["E", "", "tr", ""],
  ["E", "", "td", ""],
  ["E", "", "font", " size=-1"],
  [
    "E",
    "",
    "input",
    " id=stw type=radio name=lr value=\"\" checked",
  ],
  ["E", "", "label", " for=stw"],
  ["T", "Prohledat Internet"],
  ["E", "/", "label", ""],
  ["E", "", "input", " id=lrt type=radio name=lr value=lang_cs "],
  ["E", "", "label", " for=lrt"],
  ["T", "Vyhled\341n\355 str\341nek \350esky"],
  ["E", "/", "label", ""],
  ["E", "/", "font", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "", "tr", ""],
  ["E", "", "td", " height=7"],
  ["E", "", "img", " width=1 height=1 alt=\"\""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "/", "table", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "/", "form", ""],
  ["E", "/", "table", ""],
  ["T", "\n"],
  ["E", "", "style", ""],
  ["C", "\n.fl:link{color:#7777CC}\n"],
  ["T", "\n"],
  ["E", "/", "style", ""],
  ["T", "\n"],
  [
    "E",
    "",
    "table",
    " width=100% border=0 cellpadding=0 cellspacing=0",
  ],
  ["E", "", "tr", ""],
  ["E", "", "td", " bgcolor=#3366cc"],
  ["E", "", "img", " width=1 height=1 alt=\"\""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "/", "table", ""],
  [
    "E",
    "",
    "table",
    " width=100% border=0 cellpadding=0 cellspacing=0 bgcolor=#e5ecf9",
  ],
  ["E", "", "tr", ""],
  ["E", "", "td", " bgcolor=#e5ecf9 nowrap"],
  ["E", "", "font", " size=+1"],
  ["T", "&nbsp;"],
  ["E", "", "b", ""],
  ["T", "Web"],
  ["E", "/", "b", ""],
  ["E", "/", "font", ""],
  ["T", "&nbsp;"],
  ["E", "/", "td", ""],
  ["E", "", "td", " bgcolor=#e5ecf9 align=right nowrap"],
  ["E", "", "font", " size=-1 color=#000000"],
  ["T", "V\375sledky "],
  ["E", "", "b", ""],
  ["T", 1],
  ["E", "/", "b", ""],
  ["T", " - "],
  ["E", "", "b", ""],
  ["T", 7],
  ["E", "/", "b", ""],
  ["T", " asi "],
  ["E", "", "b", ""],
  ["T", 17],
  ["E", "/", "b", ""],
  ["T", " z "],
  ["E", "", "b", ""],
  ["T", "&quot;digitalni velkoplosny tisk&quot;"],
  ["E", "/", "b", ""],
  ["T", ".  ("],
  ["E", "", "b", ""],
  ["T", "0.26"],
  ["E", "/", "b", ""],
  ["T", " sekund)&nbsp;"],
  ["E", "/", "font", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "/", "table", ""],
  [
    "E",
    "",
    "table",
    " cellspacing=0 cellpadding=0 width=25% align=right bgColor=#ffffff border=0",
  ],
  ["E", "", "tr", ""],
  ["E", "", "td", " colspan=4"],
  ["E", "", "font", " size=-1"],
  ["T", "&nbsp;"],
  ["E", "/", "font", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "", "tr", ""],
  ["E", "", "td", " rowspan=5"],
  ["T", "&nbsp;&nbsp;"],
  ["E", "/", "td", ""],
  ["E", "", "td", " width=1 bgcolor=#c9d7f1 rowspan=5"],
  ["E", "", "img", " width=1 height=1 alt=\"\""],
  ["E", "/", "td", ""],
  ["E", "", "td", " rowspan=5"],
  ["T", "&nbsp;&nbsp;"],
  ["E", "/", "td", ""],
  ["E", "", "td", " height=25 align=center"],
  ["E", "", "font", " color=#6f6f6f size=-1"],
  ["T", "Sponzorovan\351 odkazy"],
  ["E", "/", "font", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "", "tr", " height=7"],
  ["E", "", "td", ""],
  ["E", "", "img", " width=1 height=1 alt=\"\""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "", "tr", ""],
  ["E", "", "td", " nowrap"],
  ["E", "", "font", " size=-1"],
  [
    "E",
    "",
    "a",
    " id=aw1 href=/url?q=http://www.digitalni-foto.cz&sa=l&ai=AMBdoPKdcAZ8mgYokJpd6JfMBA_IpFwuiL-YAWK4wXGgABApTw2G0GOQACEwmRAAAAAAA&num=1 onMouseOver=\"return ss('Jdi na www.kasa.cz')\" onMouseOut=\"cs()\"",
  ],
  ["T", "Digit\341ln\355 Fotoapar\341ty"],
  ["E", "/", "a", ""],
  ["E", "", "br", ""],
  ["T", "Olympus, Nikon, Canon, Fuji,"],
  ["E", "", "br", ""],
  ["T", "Karty, Pouzdra, Baterie, Stativy"],
  ["E", "", "br", ""],
  ["E", "", "font", " color=green"],
  ["T", "www.kasa.cz"],
  ["E", "/", "font", ""],
  ["E", "", "br", ""],
  ["E", "", "br", ""],
  [
    "E",
    "",
    "a",
    " id=aw2 href=/url?q=http://www.revon.cz&sa=l&ai=AmN7yPKdcAZ8mgYokJpd6JfMBPmuuFsY8I7YA1qN8UGwBCApTw2G0GOQACIwmRAAAAAAA&num=2 onMouseOver=\"return ss('Jdi na www.revon.cz')\" onMouseOut=\"cs()\"",
  ],
  ["T", "Velkoplo\271n\375 "],
  ["E", "", "b", ""],
  ["T", "tisk"],
  ["E", "/", "b", ""],
  ["E", "/", "a", ""],
  ["E", "", "br", ""],
  ["T", "Kvalita a rychlost, dobr\341 cena."],
  ["E", "", "br", ""],
  ["T", "Dok\341\276eme V\341m, \276e jsme lep\271\355!"],
  ["E", "", "br", ""],
  ["E", "", "font", " color=green"],
  ["T", "www.revon.cz"],
  ["E", "/", "font", ""],
  ["E", "/", "font", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "", "tr", " height=7"],
  ["E", "", "td", ""],
  ["E", "", "img", " width=1 height=1 alt=\"\""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "", "tr", ""],
  ["E", "", "td", " height=25 align=center"],
  ["E", "", "font", " size=-1"],
  [
    "E",
    "",
    "a",
    " href=http://www.google.com/url?q=http%3a%2f%2fadwords.google.com%2fselect%2fmain%3Fcmd=Login%26sourceid=promo%26subid=rp%26hl=cs class=fl",
  ],
  ["T", "Zde m\371\276e b\375t va\271e reklama ..."],
  ["E", "/", "a", ""],
  ["E", "/", "font", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "/", "table", ""],
  ["E", "", "table", " cellpadding=0 cellspacing=0 border=0"],
  ["T", " "],
  ["E", "", "tr", ""],
  ["E", "", "td", " valign=bottom height=30"],
  ["T", "  "],
  ["E", "", "font", " size=-1"],
  ["E", "", "font", " color=#cc0000"],
  ["T", "Tip:"],
  ["E", "/", "font", ""],
  [
    "T",
    " U\271et\370ete \350as stisknut\355m kl\341vesy Enter nam\355sto klik\341n\355 na tla\350\355tko \"Vyhledat Googlem\"",
  ],
  ["E", "/", "font", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "/", "table", ""],
  ["E", "", "div", ""],
  ["E", "", "p", " class=g"],
  [
    "E",
    "",
    "a",
    " href=http://katalog.centrum.cz/kat.php?op=section&sid=5496",
  ],
  [
    "T",
    "Centrum.cz Katalog - Obchod a sluzby - Sluzby - Reklama - Grafici ",
  ],
  ["E", "", "b", ""],
  ["T", "..."],
  ["E", "/", "b", ""],
  ["E", "/", "a", ""],
  ["E", "", "table", " cellpadding=0 cellspacing=0 border=0"],
  ["E", "", "tr", ""],
  ["E", "", "td", " class=j"],
  ["E", "", "font", " size=-1"],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "..."],
  ["E", "/", "b", ""],
  ["T", " s ro - Praha 6, "],
  ["E", "", "b", ""],
  ["T", "Digitalni"],
  ["E", "/", "b", ""],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "velkoplosny"],
  ["E", "/", "b", ""],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "tisk"],
  ["E", "/", "b", ""],
  [
    "T",
    ", laminace velkoplosna,adjustace, samolepici \nreklama, digitalizace, tiskova priprava,ramovani Tel.: 233339739. ",
  ],
  ["E", "", "b", ""],
  ["T", "..."],
  ["E", "/", "b", ""],
  ["T", " \n"],
  ["E", "", "br", ""],
  ["E", "", "font", " color=#008000"],
  [
    "T",
    "katalog.centrum.cz/kat.php?op=section&amp;sid=5496 -  38k - ",
  ],
  ["E", "/", "font", ""],
  [
    "E",
    "",
    "a",
    " class=fl href=http://66.102.11.104/search?q=cache:HZYxtTZeYK8J:katalog.centrum.cz/kat.php%3Fop%3Dsection%26sid%3D5496+%22digitalni+velkoplosny+tisk%22&hl=cs&ie=UTF-8&inlang=pl",
  ],
  ["T", "Archiv"],
  ["E", "/", "a", ""],
  ["T", " - "],
  [
    "E",
    "",
    "a",
    " class=fl href=/search?hl=cs&lr=&ie=UTF-8&inlang=pl&q=related:katalog.centrum.cz/kat.php%3Fop%3Dsection%26sid%3D5496",
  ],
  ["T", "Podobn\351&nbsp;str\341nky"],
  ["E", "/", "a", ""],
  ["E", "/", "font", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "/", "table", ""],
  ["T", " "],
  ["E", "", "blockquote", " class=g"],
  ["E", "", "p", " class=g"],
  [
    "E",
    "",
    "a",
    " href=http://katalog.centrum.cz/asc/kat.php?op=section&sid=5499",
  ],
  [
    "T",
    "Centrum.cz Katalog - Obchod a sluzby - Sluzby - Reklama - Ostatni ",
  ],
  ["E", "", "b", ""],
  ["T", "..."],
  ["E", "/", "b", ""],
  ["E", "/", "a", ""],
  ["E", "", "table", " cellpadding=0 cellspacing=0 border=0"],
  ["E", "", "tr", ""],
  ["E", "", "td", " class=j"],
  ["E", "", "font", " size=-1"],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "..."],
  ["E", "/", "b", ""],
  ["T", " Navigacni systemy na sloupech verejneho osvetleni, "],
  ["E", "", "b", ""],
  ["T", "digitalni"],
  ["E", "/", "b", ""],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "velkoplosny"],
  ["E", "/", "b", ""],
  ["T", " \n"],
  ["E", "", "b", ""],
  ["T", "tisk"],
  ["E", "/", "b", ""],
  [
    "T",
    ", signmaking, elektronicke publikovani. Tel.: 267315856. ",
  ],
  ["E", "", "b", ""],
  ["T", "..."],
  ["E", "/", "b", ""],
  ["T", " \n"],
  ["E", "", "br", ""],
  ["E", "", "font", " color=#008000"],
  [
    "T",
    "katalog.centrum.cz/asc/kat.php?op=section&amp;sid=5499 -  36k - dodate\350n\375 v\375sledek - ",
  ],
  ["E", "/", "font", ""],
  [
    "E",
    "",
    "a",
    " class=fl href=http://66.102.11.104/search?q=cache:rjXcW8w-QHUJ:katalog.centrum.cz/asc/kat.php%3Fop%3Dsection%26sid%3D5499+%22digitalni+velkoplosny+tisk%22&hl=cs&ie=UTF-8&inlang=pl",
  ],
  ["T", "Archiv"],
  ["E", "/", "a", ""],
  ["T", " - "],
  [
    "E",
    "",
    "a",
    " class=fl href=/search?hl=cs&lr=&ie=UTF-8&inlang=pl&q=related:katalog.centrum.cz/asc/kat.php%3Fop%3Dsection%26sid%3D5499",
  ],
  ["T", "Podobn\351&nbsp;str\341nky"],
  ["E", "/", "a", ""],
  ["E", "", "br", ""],
  ["T", "[ "],
  [
    "E",
    "",
    "a",
    " class=fl href=/search?hl=cs&lr=&ie=UTF-8&inlang=pl&q=+site:katalog.centrum.cz+%22digitalni+velkoplosny+tisk%22",
  ],
  ["T", "Dal\271\355 str\341nky z katalog.centrum.cz"],
  ["E", "/", "a", ""],
  ["T", " ]"],
  ["E", "/", "font", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "/", "table", ""],
  ["T", " "],
  ["E", "/", "blockquote", ""],
  ["E", "", "p", " class=g"],
  [
    "E",
    "",
    "a",
    " href=http://www.mam.cz/1-10000011-14133840-100000_detail-30",
  ],
  ["T", "MaM priloha - obalka"],
  ["E", "/", "a", ""],
  ["E", "", "table", " cellpadding=0 cellspacing=0 border=0"],
  ["E", "", "tr", ""],
  ["E", "", "td", " class=j"],
  ["E", "", "font", " size=-1"],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "..."],
  ["E", "/", "b", ""],
  [
    "T",
    " Kovar Struktura zakazek: 70 % primi klienti, 30 % agentury Technicke zazemi: vlastni \ngraficke a DTP studio Technologie tisku: ",
  ],
  ["E", "", "b", ""],
  ["T", "digitalni"],
  ["E", "/", "b", ""],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "velkoplosny"],
  ["E", "/", "b", ""],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "tisk"],
  ["E", "/", "b", ""],
  ["T", " - max. "],
  ["E", "", "b", ""],
  ["T", "..."],
  ["E", "/", "b", ""],
  ["T", " \n"],
  ["E", "", "br", ""],
  ["E", "", "font", " color=#008000"],
  [
    "T",
    "www.mam.cz/1-10000011-14133840-100000_detail-30 -  88k - ",
  ],
  ["E", "/", "font", ""],
  [
    "E",
    "",
    "a",
    " class=fl href=http://66.102.11.104/search?q=cache:A09yuIn1Pq4J:www.mam.cz/1-10000011-14133840-100000_detail-30+%22digitalni+velkoplosny+tisk%22&hl=cs&ie=UTF-8&inlang=pl",
  ],
  ["T", "Archiv"],
  ["E", "/", "a", ""],
  ["T", " - "],
  [
    "E",
    "",
    "a",
    " class=fl href=/search?hl=cs&lr=&ie=UTF-8&inlang=pl&q=related:www.mam.cz/1-10000011-14133840-100000_detail-30",
  ],
  ["T", "Podobn\351&nbsp;str\341nky"],
  ["E", "/", "a", ""],
  ["E", "/", "font", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "/", "table", ""],
  ["T", " "],
  ["E", "", "p", " class=g"],
  [
    "E",
    "",
    "a",
    " href=http://firmy.quick.cz/search/index.php?op=domain&did=5011",
  ],
  ["T", "Firmy - vyhledavani"],
  ["E", "/", "a", ""],
  ["E", "", "table", " cellpadding=0 cellspacing=0 border=0"],
  ["E", "", "tr", ""],
  ["E", "", "td", " class=j"],
  ["E", "", "font", " size=-1"],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "..."],
  ["E", "/", "b", ""],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "Digitalni"],
  ["E", "/", "b", ""],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "velkoplosny"],
  ["E", "/", "b", ""],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "tisk"],
  ["E", "/", "b", ""],
  [
    "T",
    ", laminace velkoplosna,adjustace, samolepici reklama, \ndigitalizace, tiskova priprava,ramovani web: http://www.ak-atelier.cz tel ",
  ],
  ["E", "", "b", ""],
  ["T", "..."],
  ["E", "/", "b", ""],
  ["T", " \n"],
  ["E", "", "br", ""],
  ["E", "", "font", " color=#008000"],
  [
    "T",
    "firmy.quick.cz/search/index.php?op=domain&amp;did=5011 -  101k - ",
  ],
  ["E", "/", "font", ""],
  [
    "E",
    "",
    "a",
    " class=fl href=http://66.102.11.104/search?q=cache:feKzLN7uwcoJ:firmy.quick.cz/search/index.php%3Fop%3Ddomain%26did%3D5011+%22digitalni+velkoplosny+tisk%22&hl=cs&ie=UTF-8&inlang=pl",
  ],
  ["T", "Archiv"],
  ["E", "/", "a", ""],
  ["T", " - "],
  [
    "E",
    "",
    "a",
    " class=fl href=/search?hl=cs&lr=&ie=UTF-8&inlang=pl&q=related:firmy.quick.cz/search/index.php%3Fop%3Ddomain%26did%3D5011",
  ],
  ["T", "Podobn\351&nbsp;str\341nky"],
  ["E", "/", "a", ""],
  ["E", "/", "font", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "/", "table", ""],
  ["T", " "],
  ["E", "", "p", " class=g"],
  [
    "E",
    "",
    "a",
    " href=http://firmy.centrum.cz/search/detail.php?companyID=77841",
  ],
  ["T", "Firmy - detail o firme"],
  ["E", "/", "a", ""],
  ["E", "", "table", " cellpadding=0 cellspacing=0 border=0"],
  ["E", "", "tr", ""],
  ["E", "", "td", " class=j"],
  ["E", "", "font", " size=-1"],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "..."],
  ["E", "/", "b", ""],
  ["T", " WWW: www.ak-atelier.cz. Popis "],
  ["E", "", "b", ""],
  ["T", "Digitalni"],
  ["E", "/", "b", ""],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "velkoplosny"],
  ["E", "/", "b", ""],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "tisk"],
  ["E", "/", "b", ""],
  [
    "T",
    ", laminace velkoplosna,adjustace, \nsamolepici reklama, digitalizace, tiskova priprava,ramovani. ",
  ],
  ["E", "", "b", ""],
  ["T", "..."],
  ["E", "/", "b", ""],
  ["T", " \n"],
  ["E", "", "br", ""],
  ["E", "", "font", " color=#008000"],
  [
    "T",
    "firmy.centrum.cz/search/detail.php?companyID=77841 -  24k - ",
  ],
  ["E", "/", "font", ""],
  [
    "E",
    "",
    "a",
    " class=fl href=http://66.102.11.104/search?q=cache:o96iOme-N_AJ:firmy.centrum.cz/search/detail.php%3FcompanyID%3D77841+%22digitalni+velkoplosny+tisk%22&hl=cs&ie=UTF-8&inlang=pl",
  ],
  ["T", "Archiv"],
  ["E", "/", "a", ""],
  ["T", " - "],
  [
    "E",
    "",
    "a",
    " class=fl href=/search?hl=cs&lr=&ie=UTF-8&inlang=pl&q=related:firmy.centrum.cz/search/detail.php%3FcompanyID%3D77841",
  ],
  ["T", "Podobn\351&nbsp;str\341nky"],
  ["E", "/", "a", ""],
  ["E", "/", "font", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "/", "table", ""],
  ["T", " "],
  ["E", "", "p", " class=g"],
  [
    "E",
    "",
    "a",
    " href=http://www.atila.cz/sluzby/tiskarny/?vol=f&page=43",
  ],
  ["T", "- sluzby - tiskarny - - - Vypis f"],
  ["E", "/", "a", ""],
  ["E", "", "table", " cellpadding=0 cellspacing=0 border=0"],
  ["E", "", "tr", ""],
  ["E", "", "td", " class=j"],
  ["E", "", "font", " size=-1"],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "..."],
  ["E", "/", "b", ""],
  [
    "T",
    " Sidlo firmy : Velka hradebni 3121/50, Usti nad Labem 40001 kontakt. \nXL Tisk ",
  ],
  ["E", "", "b", ""],
  ["T", "Digitalni"],
  ["E", "/", "b", ""],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "velkoplosny"],
  ["E", "/", "b", ""],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "tisk"],
  ["E", "/", "b", ""],
  ["T", " - inkjet, DTP studio. Sidlo "],
  ["E", "", "b", ""],
  ["T", "..."],
  ["E", "/", "b", ""],
  ["T", " \n"],
  ["E", "", "br", ""],
  ["E", "", "font", " color=#008000"],
  [
    "T",
    "www.atila.cz/sluzby/tiskarny/?vol=f&amp;page=43 -  29k - dodate\350n\375 v\375sledek - ",
  ],
  ["E", "/", "font", ""],
  [
    "E",
    "",
    "a",
    " class=fl href=http://66.102.11.104/search?q=cache:MEA8GoIBB04J:www.atila.cz/sluzby/tiskarny/%3Fvol%3Df%26page%3D43+%22digitalni+velkoplosny+tisk%22&hl=cs&ie=UTF-8&inlang=pl",
  ],
  ["T", "Archiv"],
  ["E", "/", "a", ""],
  ["T", " - "],
  [
    "E",
    "",
    "a",
    " class=fl href=/search?hl=cs&lr=&ie=UTF-8&inlang=pl&q=related:www.atila.cz/sluzby/tiskarny/%3Fvol%3Df%26page%3D43",
  ],
  ["T", "Podobn\351&nbsp;str\341nky"],
  ["E", "/", "a", ""],
  ["E", "/", "font", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "/", "table", ""],
  ["T", " "],
  ["E", "", "blockquote", " class=g"],
  ["E", "", "p", " class=g"],
  [
    "E",
    "",
    "a",
    " href=http://www.atila.cz/sluzby/reklama/?page=3&vol=f",
  ],
  ["T", "- sluzby - reklama a marketing - - - Vypis f"],
  ["E", "/", "a", ""],
  ["E", "", "table", " cellpadding=0 cellspacing=0 border=0"],
  ["E", "", "tr", ""],
  ["E", "", "td", " class=j"],
  ["E", "", "font", " size=-1"],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "..."],
  ["E", "/", "b", ""],
  [
    "T",
    " Edward Fencl - LOGUS Folie, grafika, rezana reklama, samolepky, stity, auta, \nsitotisk, signmaking, sazba, ",
  ],
  ["E", "", "b", ""],
  ["T", "digitalni"],
  ["E", "/", "b", ""],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "velkoplosny"],
  ["E", "/", "b", ""],
  ["T", " "],
  ["E", "", "b", ""],
  ["T", "tisk"],
  ["E", "/", "b", ""],
  ["T", ", gravirovani, neony "],
  ["E", "", "b", ""],
  ["T", "..."],
  ["E", "/", "b", ""],
  ["T", " \n"],
  ["E", "", "br", ""],
  ["E", "", "font", " color=#008000"],
  [
    "T",
    "www.atila.cz/sluzby/reklama/?page=3&amp;vol=f -  29k - dodate\350n\375 v\375sledek - ",
  ],
  ["E", "/", "font", ""],
  [
    "E",
    "",
    "a",
    " class=fl href=http://66.102.11.104/search?q=cache:4KWEZJ--E-0J:www.atila.cz/sluzby/reklama/%3Fpage%3D3%26vol%3Df+%22digitalni+velkoplosny+tisk%22&hl=cs&ie=UTF-8&inlang=pl",
  ],
  ["T", "Archiv"],
  ["E", "/", "a", ""],
  ["T", " - "],
  [
    "E",
    "",
    "a",
    " class=fl href=/search?hl=cs&lr=&ie=UTF-8&inlang=pl&q=related:www.atila.cz/sluzby/reklama/%3Fpage%3D3%26vol%3Df",
  ],
  ["T", "Podobn\351&nbsp;str\341nky"],
  ["E", "/", "a", ""],
  ["E", "", "br", ""],
  ["T", "[ "],
  [
    "E",
    "",
    "a",
    " class=fl href=/search?hl=cs&lr=&ie=UTF-8&inlang=pl&q=+site:www.atila.cz+%22digitalni+velkoplosny+tisk%22",
  ],
  ["T", "Dal\271\355 str\341nky z www.atila.cz"],
  ["E", "/", "a", ""],
  ["T", " ]"],
  ["E", "/", "font", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "/", "table", ""],
  ["T", " "],
  ["E", "/", "blockquote", ""],
  ["T", " "],
  ["E", "", "p", ""],
  ["E", "", "i", ""],
  [
    "T",
    "Abychom zobrazovali ty nejrelevantn\354j\271\355 odkazy, vynech\341v\341me n\354kter\351 z\341znamy, velmi podobn\351 7 ji\276 zobrazen\375m. ",
  ],
  ["E", "", "br", ""],
  ["T", " P\370ejete-li si, m\371\276ete  "],
  [
    "E",
    "",
    "a",
    " href=\"/search?q=%22digitalni+velkoplosny+tisk%22&hl=cs&lr=&ie=UTF-8&inlang=pl&filter=0\"",
  ],
  [
    "T",
    " zopakovat vyhled\341v\341n\355 se zobrazen\355m vynechan\375ch polo\276ek",
  ],
  ["E", "/", "a", ""],
  ["T", "."],
  ["E", "/", "i", ""],
  ["E", "", "br", ""],
  ["E", "/", "div", ""],
  ["E", "", "br", " clear=all"],
  ["E", "", "center", ""],
  ["T", "\n"],
  ["E", "", "br", " clear=all"],
  ["E", "", "br", ""],
  [
    "E",
    "",
    "table",
    " cellspacing=0 cellpadding=0 border=0 width=\"100%\"",
  ],
  ["E", "", "tr", ""],
  ["E", "", "td", " class=k"],
  ["E", "", "img", " height=1 alt=\"\" width=1"],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "", "tr", ""],
  ["E", "", "td", " align=center bgcolor=#e5ecf9"],
  ["T", "&nbsp;"],
  ["E", "", "br", ""],
  [
    "E",
    "",
    "table",
    " border=0 cellpadding=0 cellspacing=0 align=center",
  ],
  ["E", "", "form", " method=GET action=/search"],
  ["E", "", "tr", ""],
  ["E", "", "td", " nowrap"],
  ["T", "\n"],
  ["E", "", "font", " size=-1"],
  [
    "E",
    "",
    "input",
    " type=text name=q size=31 maxlength=2048 value=\"&quot;digitalni velkoplosny tisk&quot;\"",
  ],
  ["T", " "],
  [
    "E",
    "",
    "input",
    " type=submit name=btnG VALUE=\"Vyhledat Googlem\"",
  ],
  ["E", "", "input", " type=hidden name=hl value=\"cs\""],
  ["E", "", "input", " type=hidden name=inlang value=\"pl\""],
  ["E", "", "input", " type=hidden name=ie value=\"ISO-8859-2\""],
  ["E", "/", "font", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "/", "form", ""],
  ["E", "/", "table", ""],
  ["E", "", "br", ""],
  ["E", "", "font", " size=-1"],
  [
    "E",
    "",
    "a",
    " href=/swr?q=%22digitalni+velkoplosny+tisk%22&hl=cs&lr=&ie=UTF-8&inlang=pl&swrnum=17",
  ],
  ["T", "Hledat ve v\375sledc\355ch."],
  ["E", "/", "a", ""],
  ["T", " | "],
  [
    "E",
    "",
    "a",
    " href=/language_tools?q=%22digitalni+velkoplosny+tisk%22&hl=cs&lr=&ie=UTF-8&inlang=pl",
  ],
  ["T", "V\375b\354r jazyka"],
  ["E", "/", "a", ""],
  ["T", " | "],
  ["E", "", "a", " href=/intl/cs/help.html"],
  ["T", "Tipy pro vyhled\341v\341n\355"],
  ["E", "/", "a", ""],
  ["E", "/", "font", ""],
  ["E", "", "br", ""],
  ["E", "", "br", ""],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "", "tr", ""],
  ["E", "", "td", " class=k"],
  ["E", "", "img", " height=1 alt=\"\" width=1"],
  ["E", "/", "td", ""],
  ["E", "/", "tr", ""],
  ["E", "/", "table", ""],
  ["E", "/", "center", ""],
  ["E", "", "center", ""],
  ["E", "", "p", ""],
  ["E", "", "hr", " class=z"],
  [
    "E",
    "",
    "table",
    " width=100% cellpadding=2 cellspacing=0 border=0",
  ],
  ["E", "", "tr", ""],
  ["E", "", "td", " align=center"],
  ["E", "", "font", " size=-1"],
  ["E", "/", "font", ""],
  ["E", "/", "table", ""],
  ["E", "", "br", ""],
  ["E", "", "font", " size=-1 class=p"],
  ["T", "&copy;2004 Google"],
  ["E", "/", "font", ""],
  ["E", "/", "center", ""],
  ["E", "/", "body", ""],
  ["E", "/", "html", ""],
  ["T", "\r\n"],
]